config/routes.rb
Rails.application.routes.draw do
  root to: "home#feed"

  get  "/feeds/albums", to: "home#feed_albums", as: :feed_albums
  get  "/discovery", to: "home#discovery", as: :discovery
  get  "/discovery/albums", to: "home#discovery_albums", as: :discovery_albums

  post "follow/:user_id", to: "users#follow", as: :follow_user
  delete "unfollow/:user_id", to: "users#unfollow", as: :unfollow_user

  post "likes/:post_type/:post_id", to: "users#like", as: :like_post
  delete "likes/:post_type/:post_id", to: "users#unlike", as: :dislike_post
  
  scope "/profile/:id" do 
    get "/", to: "users#show", as: :profile
    get "/albums", to: "users#show_albums", as: :profile_albums
    get "/followings", to: "users#show_followings", as: :profile_followings
    get "/followers", to: "users#show_followers",  as: :profile_followers
  end

  resources :photos, except: [:index, :destroy]
  resources :albums, except: [:index, :destroy]

  namespace :admin do
    root  "users#index", as: "admin"  
    resources :photos, only: [:index, :update, :edit]
    resources :albums, only: [:index, :update, :edit]
    resources :users, except: [:create, :new]
  end 

  scope "/search" do 
    get '/all', to: "home#search",  as: "search"
    get '/photos', to: "photos#search", as: "search_photos"
    get '/albums', to: "albums#search", as: "search_albums"
    get '/users', to: "users#search",  as: "search_users"
  end 

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations' ,
    omniauth_callbacks: "users/omniauth_callbacks",
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  paginates_per 25
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]

  attr_readonly :role
  before_create :set_default_value
  before_destroy :delete_dependency
  # validates :fname, presence: true,
  validates :email, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validates :fname, length: {maximum: 25}
  validates :lname, length: {maximum: 25}
  # validates :role, inclusion: {in: %w(user admin)}

  has_many :photos, through: :albums, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :albums , dependent: :destroy


  has_many :followers_connections, class_name: "Connection", foreign_key: 'following_id'
  has_many :followings_connections, class_name: "Connection", foreign_key: 'follower_id'

  has_many :followers, through: :followers_connections, source: :follower
  has_many :followings, through: :followings_connections, source: :following

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [200, 200]
  end
  has_many :likes, dependent: :destroy

  has_many :notifications, as: :recipient, dependent: :destroy

  def follow? (user_id)
    Connection.where(follower_id: self.id, following_id: user_id ).exists?
  end

  def like?(post_or_post_id, post_type = nil)
    if post_type.nil?
      post = post_or_post_id
      self.likes.exists?(likeable_id: post.id, likeable_type: post.class.to_s)
    else
      self.likes.exists?(likeable_id: post_or_post_id, likeable_type: post_type)
    end
  end

  def admin? 
    self.role == "admin"
  end

  def fullname 
    self.fname + " " + self.lname 
  end

  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.fname = auth.info.name 
      user.avatar.attach(io: URI.open(auth.info.image), filename: "avatar#{auth.uid}") 
    end
  end



  private

  def set_default_value
      !self.role && self.role = "user"  
      !self.fname && self.fname = ""
      !self.lname && self.lname = ""
      attach_default_avatar unless avatar.attached?
      # !self.avatar && self.avatar.attach(io: File.open("#{Rails.root}/app/assets/images/default-avatar.png'), filename: 'default-avatar.png"))
  end

  def attach_default_avatar
    default_avatar_path = Rails.root.join("app/assets/images/default-avatar.png")
    self.avatar.attach(io: File.open(default_avatar_path), filename: "default-avatar.png")
  end


  def delete_dependency
    # Remove the connections from followers and followings
    self.followers.delete_all
    self.followings.delete_all
  end 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.order(:created_at).page params[:page]
    render 'users/index'
  end

  def edit
    @user = User.find_by({id: params[:id]})
    render "users/edit"
  end

  def update 
    puts params
    if User.exists?(params[:id])
      if params[:user][:password].blank?
        puts "fdf"
        User.find(params[:id]).update(user_params_without_password)
      else
        
        puts "have password"
        User.find(params[:id]).update(user_params)
      end
      redirect_to admin_users_path
    end 
  end

  def destroy
    user = User.find(params[:id])
    user.destroy!
    redirect_to admin_users_path
  end

  private
    def user_params
      params.required(:user).permit(:email, :fname, :lname, :avatar, :password)
    end

    def user_params_without_password
      params.required(:user).permit(:email, :fname, :lname, :avatar)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
  
  def google_oauth2
    user = User.from_omniauth(auth)
    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end
  protected
  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
  private
  def auth
    @auth ||= request.env['omniauth.auth']
  end

 

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout "profile/profile_layout", only: [:edit]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def update_resource(resource, params)
    if resource.provider == 'google_oauth2'
      params.delete('current_password')
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user! , only: [:show, :show_albums, :show_followings, :show_followers, :search]
  before_action :get_user, :only => [:show,:show_albums, :show_followings, :show_followers]

  layout "profile/profile_layout", only: [:show,:show_albums, :show_followings, :show_followers]
  
  def show
    @photos = @user.photos
  end

  def show_albums
    @albums = @user.albums
  end 
  
  def show_followings
    @followings = @user.followings
  end 

  def show_followers
    @followers = @user.followers
  end 
  
  def follow
    @user = User.exists?(params[:user_id]) && User.find(params[:user_id])
    begin
      current_user.followings_connections.new(following_id: @user.id)
      current_user.save!
      render :turbo_stream => turbo_stream.replace_all(
                              ".follow_user#{@user.id}",
                              partial: 'shared/follow_button',
                              locals: { user: @user } )
    rescue  Exception => e
      render :json => e
      # render file: "#{Rails.root}/public/500.html", layout: true
    end
  end

  def unfollow
    @user = User.exists?(params[:user_id]) && User.find(params[:user_id])
    begin
      current_user.followings_connections.where(following_id: @user.id).delete_all
      current_user.save!

      render :turbo_stream => turbo_stream.replace_all(
          ".follow_user#{@user.id}",
          partial: 'shared/follow_button',
          locals: { user: @user} )
    rescue  Exception => e
      render file: "#{Rails.root}/public/500.html", layout: true
    end
  end

  def like
    respond_to do |format|
      unless ['photos', 'albums'].include?(params[:post_type])
        format.json { render json: { error: "Invalid post_type" }, status: :unprocessable_entity }
      else
        post_type = (params[:post_type] == 'photos') ? Photo : Album
        current_user.likes.new({likeable_id: params[:post_id], likeable_type: post_type })
        post = post_type.find(params[:post_id])
        if current_user.save!
          format.turbo_stream do
            render :turbo_stream => turbo_stream.replace(
              "like_post_#{params[:post_id]}",
              partial: 'shared/like_button',
              locals: { post: post } )
          end
        else 
          format.json { render json:  {error: like.errors, params: params} }
        end
      end 
    end 
  end

  def unlike
    respond_to do |format|
      unless ['photos', 'albums'].include?(params[:post_type])
        format.json { render json: { error: "Invalid post_type" }, status: :unprocessable_entity }
      else
        post_type = (params[:post_type] == 'photos') ? Photo : Album
        current_user.likes.where(likeable_id: params[:post_id], likeable_type: post_type.to_s).delete_all
        post = post_type.find(params[:post_id])
        
        if current_user.save!
          format.turbo_stream do
            render :turbo_stream => turbo_stream.replace(
              "like_post_#{params[:post_id]}",
              partial: 'shared/like_button',
              locals: { post: post } )
          end
        else 
          format.json { render json:  {error: like.errors, params: params} }
        end
      end 
    end 
  end

  def search
    if params[:key] && params[:key] != ""
      key = User.sanitize_sql_like(params[:key])
      @results = User.where("fname LIKE ? OR lname LIKE ?", "%#{key}%", "%#{key}%").limit(20)
      render "users/search_result", layout: "search/search_layout"
    else
      render :html => "Must have a key to search!"
    end
  end


  private
    def get_user
      if User.exists?(params[:id])
        @user = User.find(params[:id])
        if current_user 
          @is_owner = @user.id == current_user.id
        end
      else 
        render file: "#{Rails.root}/public/404.html", layout: true, status: :not_found
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow-list.html.erb
<div class="contanter-fluid">
  <div class='row'> 
    <% follows.each do |user| %>
      <div class = "card col-md-3 text-center border-0">
        <div class="bg-light py-4 px-2 my-3 border border-warning rounded shadow" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <%= link_to image_tag(user.avatar, class: "w-50 rounded-circle border border-2 border-primary" ), profile_path(user.id)%>
          <p class='my-2 fw-bold'> <%= user.fname + " " + user.lname %> </p>
          <div class="d-flex justify-content-center my-2">
            <div class="mx-2">
                <p class="fs-3 text-primary fw-bold my-0"><%= user.photos.size %></p>
                <span class="fs-5 text-dark">Photos</span>
            </div>
            <div class="mx-2">
                <p class="fs-3 text-primary fw-bold my-0"><%= user.albums.size %></p>
                <span class="fs-5 text-dark">albums</span>
            </div>
          </div>
          <%= render partial: "shared/follow_button", locals: {user: user} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_posts-list.html.erb
<% if @is_owner %>
  <div class='row px-3'>
      <%= link_to "Add new #{post_type =='photos' ? "photos" : "albums"}", post_type =='photos' ? new_photo_path : new_album_path, class: "btn btn-success w-25 ms-auto" %>
  </div>
<% end %>
<div class='row'> 
  <% if posts.size > 0 %>
    <% posts.each do |post| %>
      <% is_photo = post.is_a?(Photo) %>
      <div class="card col-md-3 col-6 post-item p-3 border-0 text-center">
        <%= link_to is_photo ? photo_path(post.id) : album_path(post.id), class: 'text-decoration-none text-dark', data: { turbo_frame: "remote_modal" } do %>
          <div class="position-relative post-image-container position-relative" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <% if is_photo %>
              <%= image_tag(post.image.attached? && post.image, class: "img-fluid rounded-start post-image") %>
            <% else %>
              <% post.photos.each do |photo| %>
                <%= image_tag photo.image, class: "img-fluid rounded-start post-image" %>
              <% end %>
            <% end %> 

            <% if post.sharing_mode == 'private' && current_user && current_user.id == post.user.id%>
              <%= link_to is_photo ? edit_photo_path(post) : edit_album_path(post), class: "btn btn-light position-absolute rounded-circle m-2 z-100", style: "top: 0; right: 0;" do %>
                <i class="fa-solid fa-lock"></i>
              <% end %>
            <% end %> 

            <% if post.is_a?(Album) %>
              <span class="position-absolute rounded-circle text-white z-100 home-image-counter">
                <b class='text-center m-0 fs-4'><%= post.photos.size %></b>
                <p class='text-center m-0'>PHOTOS</p>
              </span>
            <% end %>
            <% if @is_owner %>
              <%= link_to "Edit", is_photo ? edit_photo_path(post) : edit_album_path(post), class: "bg-dark-rgba text-white text-decoration-none px-2 py-1 rounded position-absolute m-2 border-0 z-100", style: "bottom: 8px; right: 0;" %>
            <% end %>  
          </div>
          <p class="mt-2 line-1"><%= post.title%></p>

        <% end %>
      </div>
    <% end %> 
  <% else %>
    <%= render partial: "shared/empty_record", locals: {record: "photo"}%>
  <% end %>
</div>

app/views/users/_search_item.html.erb
<li class="d-flex align-items-center border py-3 px-3  my-2 rounded">
  <%= link_to profile_path(user.id), class: "d-flex align-items-center text-decoration-none" do %>
    <%= image_tag(user.avatar, class: "mini-avatar border-primary") %>
    <p class="m-0 ms-3 text-dark fw-regular"><%= user.fullname %></p>
  <% end %>
  <div class="ms-auto">
    <%= render partial: "shared/follow_button", locals: {user: user} %>
  </div>
</li>

app/views/users/edit.html.erb
<%= render "shared/remote_modal", title: "Edit user" do %>	
   <%= form_with(model: [:admin, @user]) do |f| %>
    <div class="field form-group d-flex justify-content-center my-2 w-100" data-controller="preview">
        <%= f.file_field :avatar, class: "image-frame" %>
        <%= f.label :avatar, id: "avatar-preview", class: "profile__avatar border", style: "background: url('#{url_for(current_user.avatar)}') center / cover no-repeat ; aspect-ratio: 1/1;" do %>
          <span class="bg-light text-dark mb-2 bg-opacity-75 shadow px-4 py-1 rounded">CHANGE</span>
        <% end %>
    </div>
    <p class="text-primary fw-bold">Basic infomation</p>

    <div class="field form-group d-flex align-items-center my-2">
      <%= f.label :email, class: 'text-nowrap col-3' %>
      <%= f.email_field :email, autofocus: true, autocomplete: "first name", class:"form-control mx-sm-3 w-100" %>
    </div>

    <div class="field form-group d-flex align-items-center my-2">
      <%= f.label "First name" , class: 'text-nowrap col-3'%>
      <%= f.text_field :fname, autofocus: true, autocomplete: "fname", class:"form-control mx-sm-3 w-100" %>
    </div>

    <div class="field form-group d-flex align-items-center my-2">
      <%= f.label "Last name", class: 'text-nowrap col-3' %>
      <%= f.text_field :lname, autofocus: true, autocomplete: "email", class:"form-control mx-sm-3 w-100" %>
    </div>

    <div class="field form-group d-flex align-items-center my-2">
      <%= f.label :password, "Password", class: 'text-nowrap col-3' %>
      <%= f.password_field :password, class:"form-control mx-sm-3 w-100" %>
    </div>

    <div class="actions w-100 text-center">
      <%= f.submit "Save change", class: "btn btn-primary" %>
    </div>
  <% end %> 
<% end %>

app/views/users/index.html.erb
 <div class="bg-light  table-responsive shadow-lg mt  -3 px-2 rounded ">
  <header class="d-flex align-items-center justify-content-between border-bottom p-2 my-2">
    <span class="fw-bold fs-4">Manage users</span>
  </header>
  <table class="table table-hover flex-fill mb-4">
    <thead class="position-sticky top-0 bg-white rounded" >
      <tr>
        <th scope="col">ID</th>
        <th scope='col'></th>
        <th scope="col">Firstname</th>
        <th scope="col">Lastname</th>
        <th scope="col">Email</th>
        <th scope="col">Last login</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr data-user-id="<%= user.id %>">
          <th scope="row"><%=user.id %></th>
          <td><%= image_tag user.avatar,class:'rounded-circle border', style: 'width: 30px; height: 30px;'%> </td> 
          <td><%=user.fname %></td>
          <td><%=user.lname %></td>
          <td><%=user.email %></td>
          <td><%=user.created_at %></td>
          <td class="d-flex">
              <%= link_to "Edit", edit_admin_user_path(user.id), class: "btn btn-success me-2",  data: { turbo_frame: "remote_modal" } %>
              <%= link_to "Delete", "#", class: 'btn btn-danger',
                data: {
                    controller: "confirm",
                    action: "confirm#click",
                    confirm_title_value: "Delete this user?",
                    confirm_message_value: "<p>Are you sure you want to delete this user?<p>",
                    confirm_ok_button_value: "Delete",
                    confirm_url_value: admin_user_path(user.id),
                    confirm_method_value: "delete"
                  } %> 
          </td>
        </tr> 
      <% end %>
    </tbody>

  </table>
</div>
  <%= paginate @users, theme: 'bootstrap-5',
                  pagination_class: "pagination-sm flex-wrap justify-content-center mx-auto my-2",
                  nav_class: "d-flex w-100 position-sticky bottom-0 left-0 bg-white shadow rounded" %>	

app/views/users/search_result.html.erb
<div class=" col-10 mx-auto px-3 bg-light my-5 rounded"> 
  <ul class="shadow p-3 rounded shadow border">
    <% @results.each do |user| %>
      <%= render partial: "users/search_item", locals: {user: user} %>
    <% end %>
  
    <%= link_to "More ...", search_photos_path(@key), class: "btn btn-light border mt-3 fw-bold w-100" %>
  </ul>
</div>

app/views/users/show.html.erb
<%= render "shared/profile_info", user: @user %>
<div class="mt-4 h-100">
  <%= render partial: 'users/posts-list', locals: {posts: @photos, post_type: 'photos'} %>
</div>

app/views/users/show_albums.html.erb
<%= render "shared/profile_info", user: @user %>
<div class="mt-4">
  <%= render partial: 'users/posts-list', locals: {posts: @albums, post_type: 'albums'} %>
</div>

app/views/users/show_followers.html.erb
<%= render "shared/profile_info", user: @user %>
<div class="mt-4">
  <%= render partial: 'users/follow-list', object: @followers, as: "follows" %>
</div>

app/views/users/show_followings.html.erb
<%= render "shared/profile_info", user: @user %>
<div class="mt-4">
  <%= render partial: 'users/follow-list', object: @followings, as: "follows" %>
</div>