config/routes.rb
Rails.application.routes.draw do
  root to: "home#feed"

  get  "/feeds/albums", to: "home#feed_albums", as: :feed_albums
  get  "/discovery", to: "home#discovery", as: :discovery
  get  "/discovery/albums", to: "home#discovery_albums", as: :discovery_albums

  post "follow/:user_id", to: "users#follow", as: :follow_user
  delete "unfollow/:user_id", to: "users#unfollow", as: :unfollow_user

  post "likes/:post_type/:post_id", to: "users#like", as: :like_post
  delete "likes/:post_type/:post_id", to: "users#unlike", as: :dislike_post
  
  scope "/profile/:id" do 
    get "/", to: "users#show", as: :profile
    get "/albums", to: "users#show_albums", as: :profile_albums
    get "/followings", to: "users#show_followings", as: :profile_followings
    get "/followers", to: "users#show_followers",  as: :profile_followers
  end

  resources :photos, except: [:index, :destroy]
  resources :albums, except: [:index, :destroy]

  namespace :admin do
    root  "users#index", as: "admin"  
    resources :photos, only: [:index, :update, :edit]
    resources :albums, only: [:index, :update, :edit]
    resources :users, except: [:create, :new]
  end 

  scope "/search" do 
    get '/all', to: "home#search",  as: "search"
    get '/photos', to: "photos#search", as: "search_photos"
    get '/albums', to: "albums#search", as: "search_albums"
    get '/users', to: "users#search",  as: "search_users"
  end 

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations' ,
    omniauth_callbacks: "users/omniauth_callbacks",
  }

end

app/views/shared/_album_form.html.erb
<header class="d-flex align-items-center justify-content-between py-2 border-bottom">
  <span class="fw-bold"><%= title %></span>
    <%= link_to "Back", :back,  class: "btn btn-primary px-4 "%>
</header>
<%= form_with(model: model ,html: {class: "container g-3 needs-validation my-3", novalidate: true }) do |f| %>
  <div class="row">
    <div class="col-12 col-md-6">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control", required: true %>
    
      <div class="col-12 col-md-6 mt-4">
        <%= f.label :sharing_mode, class: "form-label" %>
        <%= f.select :sharing_mode, options_for_select([["Private", "private"],["Public", "public"] ], :selected => @album.sharing_mode),{}, class: "form-select w-100" %>
      </div>
    </div>
    <div class="col-md-6 mt-4 mt-md-0 d-flex flex-column">
      <%= f.label :description, class:"form-label" %>
      <%= f.text_area :description, class: "form-control flex-grow-1", required: true %>
      <div class="invalid-feedback h-auto">
          Please provide a valid description.
      </div>
    </div>
    <%= yield %>
    <div class="mt-4 col-md-12 d-flex flex-column justify-content-start" data-controller="preview"> 
      <div id="imagesUploadedPreview" class="row imagesUploadedPreview">
        <%= yield :imagesUploaded %>
      </div>
      <div id="imagePreview" class="row"></div>
			<div class="row">
		  	<%= f.fields_for :images do |p| %>
          <div class="field">
            <%= f.label :images, class: "image-label d-flex", for: "imageInput" do %>
              <i class="fa-solid fa-plus plus-symbol m-auto"></i>
            <% end %>
            <%= p.file_field :image_link, multiple: true, class: "image-frame", id: "imageInput", name: "[images][]" %>
          </div>
			  <% end %>

			</div>
    </div>
    <div class="col-12 mt-4">
      <%= f.submit "Save", class: "btn btn-success px-4 me-2" %>
      <% if @album.user %>
        <%= f.submit "Delete", class: "btn btn-danger px-4 me-2", :name => 'delete' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_edit_user_form.html.erb
 <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>
  <div class="field form-group d-flex justify-content-center my-2 w-100" data-controller="preview">
      <%= f.file_field :avatar, class: "image-frame" %>
      <%= f.label :avatar, id: "avatar-preview", class: "profile__avatar border", style: "background: url('#{url_for(current_user.avatar)}') center / cover no-repeat ; aspect-ratio: 1/1;" do %>
        <span class="bg-light text-dark mb-2 bg-opacity-75 shadow px-4 py-1 rounded">CHANGE</span>
      <% end %>
  </div>
  <p class="text-primary fw-bold">Basic infomation</p>

  <div class="field form-group d-flex align-items-center my-2">
    <%= f.label :email, class: 'text-nowrap col-3' %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control mx-sm-3 w-100" %>
  </div>

  <div class="field form-group d-flex align-items-center my-2">
    <%= f.label "First name" , class: 'text-nowrap col-3'%>
    <%= f.text_field :fname, autofocus: true, autocomplete: "email", class:"form-control mx-sm-3 w-100" %>
  </div>

  <div class="field form-group d-flex align-items-center my-2">
    <%= f.label "Last name", class: 'text-nowrap col-3' %>
    <%= f.text_field :lname, autofocus: true, autocomplete: "email", class:"form-control mx-sm-3 w-100" %>
  </div>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="field form-group d-flex align-items-center my-2">
    <%= f.label :current_password , class: 'text-nowrap col-3'%> 
    <%= f.password_field :current_password, autocomplete: "current-password", class:"form-control mx-sm-3 w-100" %>
    <i>(we need your current password to confirm your changes)</i><br />
  </div> 


  <div class="actions w-100 text-center">
    <%= f.submit "Save change", class: "btn btn-primary" %>
  </div>
<% end %> 

app/views/shared/_empty_album.html.erb
<%= image_tag "empty_album.jpg" , class: "img-fluid rounded-start post-image" %>

app/views/shared/_empty_record.html.erb
<div class="empty-state mx-auto d-flex justify-content-center">
  <div class="empty-state__content">
    <div class="empty-state__icon text-center">
      <%= image_tag "empty_icon.png" %>
      <h5 class="empty-state__message">No <%= record %> has been added yet.</h5>
    </div>
  </div>
</div>

app/views/shared/_follow_button.html.erb
<% if current_user %>
  <%= turbo_frame_tag "follow_user#{user.id}", class: "follow_user#{user.id}" do %>
    <% if current_user.follow?(user.id) %>
      <%= button_to "Following", unfollow_user_path(user.id), method: :delete, class: "btn btn-following mini" %> 
    <%else %> 
      <%= button_to "Follow", follow_user_path(user.id), method: :post, class: "btn btn-follow mini" %> 
    <%end %>
  <%end %>
<%else %>
  <%= link_to "Follow", user_session_path, class: "btn btn-following my-3" %> 
<% end %>

app/views/shared/_home_nav.html.erb
<% path = URI.parse(request.original_url).path.split('/') %>
<ul class="nav nav-pills mb-3 mx-auto home-nav" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <%= link_to "Photos", page == 'feed' ? root_path : discovery_path, 
            class: "nav-link #{"active" unless path.include?('albums')}" %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to "Albums", page == 'feed' ? feed_albums_path : discovery_albums_path,  
            class: "nav-link #{"active" if path.include?('albums')}" %>
  </li>
</ul>

app/views/shared/_infinite_scrollable.html.erb
<%= turbo_stream.append "photos" do %>
  <% @photos.each do |photo| %>
    <%= render partial: "home/photo_item", locals: {photo: photo} %>
  <% end %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: root_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/shared/_like_button.html.erb
<% if current_user %>
	<%= turbo_frame_tag "like_post_#{post.id}", class: "d-flex align-items-center" do %>
		<% if post.is_liked?(current_user.id) %>
			<%= button_to dislike_post_path(post.is_a?(Photo) ? 'photos' : 'albums', post.id), method: :delete, class: 'btn p-0 me-2' do %> 
				<i class="fa-solid fa-heart text-danger"></i>
			<% end %>
		<%else %>
			<%= button_to like_post_path(post.is_a?(Photo) ? 'photos' : 'albums', post.id), method: :post, class: "btn p-0 me-2" do %> 
				<i class="fa-regular fa-heart"></i>
			<% end %>
		<%end %>
		<span class="card-text m-0"><%= post.likes.count %></span>
	<% end %>
<%else %>
  <%= link_to user_session_path, class: "btn d-flex align-items-center" do %> 
		<i class="fa-regular fa-heart me-1"></i>
		<span class="card-text m-0"><%= post.likes.count %></span>
	<% end %>
<% end %>

app/views/shared/_pagination.html.erb
<%= paginate resource,  theme: 'bootstrap-5',
                   pagination_class: "pagination-sm flex-wrap justify-content-center",
                   nav_class: "d-inline-block" %>	

app/views/shared/_photo_form.html.erb
<header class="d-flex align-items-center justify-content-between py-2 border-bottom">
  <span class="fw-bold"><%= title %></span>
  <%= link_to "Back", :back,  class: "btn btn-primary px-4 "%>
</header>
<%= form_with(model: model ,html: {class: "container g-3 needs-validation my-3", novalidate: true }) do |f| %>
  <div class="row">
    <div class="col-12 col-md-6">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control", required: true %>
    
      <div class="col-12 col-md-6 mt-4">
        <%= f.label :sharing_mode, class: "form-label" %>
        <%= f.select :sharing_mode, options_for_select([["Private", "private"],["Public", "public"] ], :selected => @photo.sharing_mode ),{}, class: "form-select w-100" %>
      </div>
    </div>

    <div class="col-md-6 mt-4 mt-md-0 d-flex flex-column">
      <%= f.label :description, class:"form-label" %>
      <%= f.text_area :description, class: "form-control flex-grow-1", required: true %>
      <div class="invalid-feedback h-auto">
          Please provide a valid description.
      </div>
    </div>

    <div class="mt-4 col-md-12 d-flex justify-content-start" data-controller="preview">
      <div class="">
        <%= f.file_field :image , class: "image-frame", id: "photoInput"  %>
        <% if @photo.image.attached? %>
          <%= f.label :image, id: "photoPreview", for: "photoInput", class: "profile__avatar border", style: "background: url('#{url_for(@photo.image)}') center / cover no-repeat ; aspect-ratio: 1/1;" do %>
            <span class="bg-light text-dark mb-2 bg-opacity-75 shadow px-4 py-1 rounded">CHANGE</span>
          <% end %> 
        <% else %>
          <%= f.label :image, class: "image-label d-flex", for: "photoInput", id: "photoPreview" do %>
              <i class="fa-solid fa-plus plus-symbol m-auto"></i>
          <% end %>
        <% end %>
      </div>
    </div>

     <div class="col-12 mt-4">
      <%= f.submit "Save", class: "btn btn-success px-4 me-2" %>
      <% if @photo %>
        <%= f.submit "Delete", class: "btn btn-danger px-4 me-2", :name => 'delete' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_profile_info.html.erb
<div class="profile d-flex mt-4 pb-4">
  <%= image_tag user.avatar, class: "profile__avatar rounded-circle me-4 border-1 border-primary" %>
  <div class="profile-info d-flex flex-column justify-content-center align-items-start h-100"> 
    <% if current_user %>
      <% if user.id == current_user.id %>
        <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-outline-primary my-3 w-auto" %>
      <% else %>
        <%= render partial:  'shared/follow_button', locals: {user: user} %>
      <% end %>
    <% end %>
    <h2 class="my-2"><%=  user.fname + " " + user.lname %></h2>
    <ul class="nav nav-tabs border-0 d-flex">
      <% path = URI.parse(request.original_url).path.split('/')  %>
      <li class="nav-item">
        <%= link_to profile_path(user.id),  class: "nav-link border-0 fw-bold #{"active" if ((["albums", "followings", "followers" ] & path).empty?)}" do %>
          <i class='fs-5'><%= user.photos.size %> </i>photos
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to profile_albums_path(user.id),  class: "nav-link border-0 fw-bold #{"active" if path.include?("albums")}" do %>
          <i class='fs-5'><%= user.albums.size %> </i>albums
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to profile_followings_path(user.id),  class: "nav-link border-0 fw-bold #{"active" if path.include?("followings")}" do %>
          <i class='fs-5'><%= user.followings.size %> </i>followings
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to profile_followers_path(user.id),  class: "nav-link border-0 fw-bold #{"active" if path.include?("followers")}" do %>
          <i class='fs-5'><%= user.followers.size %> </i>followers
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade custom-model" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header align-items-start">
          <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %> 

app/views/shared/_success_modal.html.erb
<%= render "shared/modal", title: "Successfully" do %>

  <h1> sdjkcc cbbdc bcbc </h1>

<% end %>