config/routes.rb
Rails.application.routes.draw do
  root to: "home#feed"

  get  "/feeds/albums", to: "home#feed_albums", as: :feed_albums
  get  "/discovery", to: "home#discovery", as: :discovery
  get  "/discovery/albums", to: "home#discovery_albums", as: :discovery_albums

  post "follow/:user_id", to: "users#follow", as: :follow_user
  delete "unfollow/:user_id", to: "users#unfollow", as: :unfollow_user

  post "likes/:post_type/:post_id", to: "users#like", as: :like_post
  delete "likes/:post_type/:post_id", to: "users#unlike", as: :dislike_post
  
  scope "/profile/:id" do 
    get "/", to: "users#show", as: :profile
    get "/albums", to: "users#show_albums", as: :profile_albums
    get "/followings", to: "users#show_followings", as: :profile_followings
    get "/followers", to: "users#show_followers",  as: :profile_followers
  end

  resources :photos, except: [:index, :destroy]
  resources :albums, except: [:index, :destroy]

  namespace :admin do
    root  "users#index", as: "admin"  
    resources :photos, only: [:index, :update, :edit]
    resources :albums, only: [:index, :update, :edit]
    resources :users, except: [:create, :new]
  end 

  scope "/search" do 
    get '/all', to: "home#search",  as: "search"
    get '/photos', to: "photos#search", as: "search_photos"
    get '/albums', to: "albums#search", as: "search_albums"
    get '/users', to: "users#search",  as: "search_users"
  end 

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations' ,
    omniauth_callbacks: "users/omniauth_callbacks",
  }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:feed, :discovery, :search]
  layout "search/search_layout", only: [:search]
  def feed
    if current_user
      followed_users = Connection.where(follower_id: current_user.id).pluck(:following_id)
      @pagy, @photos = pagy(Photo.where(user_id: followed_users).order(:created_at), items: 4)
      respond_to do |format|
        format.html 
        format.turbo_stream
      end
    else
      redirect_to discovery_path
    end
  end


  def feed_albums 
    if current_user
      followed_users = Connection.where(follower_id: current_user.id).pluck(:following_id)
      @pagy, @albums = pagy(Album.where(user_id: followed_users).order(:created_at), items: 4)
      respond_to do |format|
        format.html 
        format.turbo_stream
      end
    else
      redirect_to discovery_path
    end
  end

  def discovery
    @pagy, @photos = pagy(Photo.order(:created_at), items: 4)
    respond_to do |format|
      format.html 
      format.turbo_stream
    end
  end 


  def discovery_albums
    @pagy, @albums = pagy(Album.order(:created_at), items: 4)
    respond_to do |format|
      format.html 
      format.turbo_stream
    end
  end


  def search 
    begin 
      if params[:key] && params[:key] != ""
        user_key = User.sanitize_sql_like(params[:key])
        post_key = Photo.sanitize_sql_like(params[:key])
        @key = params[:key]
        @users = User.where("fname LIKE ? OR lname LIKE ?", "%#{user_key}%", "%#{user_key}%").limit(3)
        @photos = Photo.where("title LIKE ? OR description LIKE ?", "%#{post_key}%", "%#{post_key}%").limit(2)
        @albums = Album.where("title LIKE ? OR description LIKE ?", "%#{post_key}%", "%#{post_key}%").limit(2)
        render "home/search", layout: "search/search_layout"
      else
        render :json => params
      end
    rescue Exception => e
      render :json => e
    end 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_album_item.html.erb
<div class= "card col col-12 col-md-6 post-item p-2 border-0 align-content-stretch">
  <div class="row g-0 border rounded shadow h-100">
    <div class="col-12 col-lg-5 position-relative post-image-container">
      <%if album.photos.size > 0  %>
          <%= link_to album_path(album.id), data: { turbo_frame: "remote_modal" } do %>
            <% album.photos.each do |photo| %>
              <% if photo.image.attached? %>
                <%= image_tag photo.image , class: "img-fluid rounded-start post-image w-100 h-100" %>
              <% end %>
            <% end %>
          <% end %>
      <% else %>
        <%= render "shared/empty_album" %>
      <% end %>
      <span class="position-absolute rounded-circle text-white z-100 home-image-counter">
        <b class='text-center m-0 fs-4'><%= album.photos.size %></b>
        <p class='text-center m-0'>PHOTOS</p>
      </span>
    </div>
    <div class="col-12 col-lg-7">
      <div class="card-body d-flex flex-column h-100">
        <div class="d-flex align-items-center justify-content-between mb-3">
          <%= link_to profile_path(album.user), class: "col-lg-8 d-flex align-items-center text-decoration-none text-primary me-1" do %>
            <%= image_tag album.user.avatar, class: "mini-avatar" %>
            <h6 class='ms-2 my-0 fs-7'><%= album.user.fname + " " + album.user.lname%> </h6>
          <% end %>
          <%= render partial: 'shared/follow_button', locals: {user: album.user} %> 
        </div>
        <h5 class="card-title"><%= album.title %></h5>
        <p class="card-text"><%=album.description %></p>
        <div class="d-flex justify-content-between mt-auto align-items-center">
          
          <%= render partial: "shared/like_button", locals: {post: album} %>
          <p class="card-text"><small class="text-muted"><%= album.created_at %></small></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_photo_item.html.erb
<div class= "card col col-12 col-md-6 post-item p-2 border-0 align-content-stretch">
  <div class="row g-0 border rounded shadow h-100">
    <div class="col-12 col-lg-5 position-relative post-image-container">
      <%= link_to photo_path(photo.id), data: { turbo_frame: "remote_modal" } do %>
        <%= image_tag photo.image , class: "img-fluid rounded-start post-image w-100" %>
      <% end %> 
    </div>
    <div class="col-12 col-lg-7">
      <div class="card-body d-flex flex-column h-100">
        <div class="d-flex align-items-center justify-content-between mb-3">
          <%= link_to profile_path(photo.user), class: "col-lg-8 d-flex align-items-center text-decoration-none text-primary me-1" do %>
            <%= image_tag photo.user.avatar, class: "mini-avatar" %>
            <h6 class='ms-2 my-0 fs-7'><%= photo.user.fname + " " + photo.user.lname%> </h6>
          <% end %>
          <%= render partial: 'shared/follow_button', locals: {user: photo.user} %> 
        </div>
        <h5 class="card-title"><%= photo.title %></h5>
        <p class="card-text"><%=photo.description %></p>
        <div class="d-flex justify-content-between mt-auto align-items-center">
          <%= render partial: "shared/like_button", locals: {post: photo} %>
          <p class="card-text"><small class="text-muted"><%= photo.created_at %></small></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_posts-list.html.erb
<% "https://dev.to/chwistophe/rails-7-pagination-with-turbo-frame-streams-infinite-scrolling-stimulus-js-3fih" %>
<div class="row list-posts g-2" id="posts_placeholder">
	<% posts && posts.each do |post| %>
		<% if post.is_a? Photo %>
			<%= render  "home/photo_item", photo: post %>
		<% else %>
			<%= render  "home/album_item", album: post %>
		<% end %>
	<% end %>
</div>

app/views/home/discovery.html.erb
<%= render partial: "shared/home_nav", locals: {page: "discovery"}%>
<div id="photos" class="row list-posts g-2"></div>

<%= turbo_frame_tag "pagination", src: discovery_path(format: :turbo_stream), loading: :lazy %>

app/views/home/discovery.turbo_stream.erb
<%= turbo_stream.append "photos" do %>
  <% @photos.each do |photo| %>
    <%= render partial: "home/photo_item", locals: {photo: photo} %>
  <% end %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: discovery_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/home/discovery_albums.html.erb
<%= render partial: "shared/home_nav", locals: {page: "discovery"}%>
<div id="discovery-albums" class="row list-posts g-2"></div>

<%= turbo_frame_tag "pagination", src: discovery_albums_path(format: :turbo_stream), loading: :lazy %>

app/views/home/discovery_albums.turbo_stream.erb
<%= turbo_stream.append "discovery-albums" do %>
  <% @albums.each do |album| %>
    <%= render partial: "home/album_item", locals: {album: album} %>
  <% end %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: discovery_albums_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/home/feed.html.erb
<%= render partial: "shared/home_nav", locals: {page: "feed"}%>

<div id="photos" class="row list-posts g-2">
  <% @photos.each do |photo| %>
    <%= render partial: "home/photo_item", locals: {photo: photo} %>
  <% end %>
</div>

<%= turbo_frame_tag "pagination", src: root_path(format: :turbo_stream), loading: :lazy %>

  

app/views/home/feed.turbo_stream.erb
<%= turbo_stream.append "photos" do %>
  <% @photos.each do |photo| %>
    <%= render partial: "home/photo_item", locals: {photo: photo} %>
  <% end %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: root_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/home/feed_albums.html.erb
<%= render partial: "shared/home_nav", locals: {page: "feed"}%>
<div id="feed-albums" class="row list-posts g-2"></div>

<%= turbo_frame_tag "pagination", src: feed_albums_path(format: :turbo_stream), loading: :lazy %>

app/views/home/feed_albums.turbo_stream.erb
<%= turbo_stream.append "feed-albums" do %>
  <% @albums.each do |album| %>
    <%= render partial: "home/album_item", locals: {album: album} %>
  <% end %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: feed_albums_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/home/search.html.erb
<div class=" col-10 mx-auto px-3 bg-light my-5 rounded"> 
  <% if @users.size > 0 %>
    <ul class="shadow p-3 rounded shadow border">
      <h4 class="fs-3 my-2">People</h4>
      <% @users.each do |user| %>
        <%= render partial: "users/search_item", locals: {user: user} %>
      <% end %>

      <%= link_to "More ...", search_users_path(key: @key), class: "btn btn-outline-primary border mt-3 fw-bold w-100" %>
    </ul>
  <% end %>

  <% if @photos.size > 0 %>
    <div class="shadow p-3 rounded shadow border my-3">
      <h4 class="fs-3 my-2">Photo</h4>
      <%= render  partial: 'home/posts-list', locals: {posts: @photos} %>
      <%= link_to "More ...", search_photos_path(key: @key), class: "btn btn-outline-primary border mt-3 fw-bold w-100" %>
    </div>
  <% end %>

  <% if @albums.size > 0 %>
    <div class="shadow p-3 rounded shadow border">
      <h4 class="fs-3 my-2">Album</h4>
      <%= render  partial: 'home/posts-list', locals: {posts: @albums}, data: {turbo: false} %>
      <%= link_to "More ...", search_albums_path(key: @key), class: "btn btn-outline-primary border mt-3 fw-bold w-100" %>
    </div>
  <% end %>


</div>