config/routes.rb
Rails.application.routes.draw do
  root to: "home#feed"

  get  "/feeds/albums", to: "home#feed_albums", as: :feed_albums
  get  "/discovery", to: "home#discovery", as: :discovery
  get  "/discovery/albums", to: "home#discovery_albums", as: :discovery_albums

  post "follow/:user_id", to: "users#follow", as: :follow_user
  delete "unfollow/:user_id", to: "users#unfollow", as: :unfollow_user

  post "likes/:post_type/:post_id", to: "users#like", as: :like_post
  delete "likes/:post_type/:post_id", to: "users#unlike", as: :dislike_post
  
  scope "/profile/:id" do 
    get "/", to: "users#show", as: :profile
    get "/albums", to: "users#show_albums", as: :profile_albums
    get "/followings", to: "users#show_followings", as: :profile_followings
    get "/followers", to: "users#show_followers",  as: :profile_followers
  end

  resources :photos, except: [:index, :destroy]
  resources :albums, except: [:index, :destroy]

  namespace :admin do
    root  "users#index", as: "admin"  
    resources :photos, only: [:index, :update, :edit]
    resources :albums, only: [:index, :update, :edit]
    resources :users, except: [:create, :new]
  end 

  scope "/search" do 
    get '/all', to: "home#search",  as: "search"
    get '/photos', to: "photos#search", as: "search_photos"
    get '/albums', to: "albums#search", as: "search_albums"
    get '/users', to: "users#search",  as: "search_users"
  end 

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations' ,
    omniauth_callbacks: "users/omniauth_callbacks",
  }

end

app/views/layouts/_admin_navbar.html.erb
<div class="bg-primary py-1 d-flex m-auto px-3" id="header">
  <header class="header w-100 px-3 py-2 d-flex align-items-center">
    <button  class='sidebar-toggle-btn btn text-white border-0 p-0 pe-3 d-flex align-items-center'>
      <i class="fa-solid fa-bars fs-4"></i>
    </button>
    <%= link_to "Fotobook Admin", root_path, class: "text-white h2 m-0 text-decoration-none" %>
    <%= form_tag search_path, method: :get, class: "form-group search-form" do %>
      <div class="input-group w-0 position-relative px-2 d-none d-md-flex">
        <%= text_field_tag :key, "" , class: "form-control search-form__text--input w-auto rounded", placeholder: "Search for photos/albums..." %>
        <button class="input-icon-right btn btn-light cursor-pointer rounded">
          <i class="fa-solid fa-magnifying-glass text-dark"></i>
        </button>
      </div>
    <% end %>

    <%= link_to(profile_path(current_user), class: 'user-info d-flex ms-auto align-items-center text-white text-decoration-none') do %>
      <%= image_tag(current_user.avatar, class: "user-info__avatar rounded-circle border") if current_user.avatar.attached? %>
      <span class="ms-2"><%= current_user.fname + " " + current_user.lname %></span>
    <% end %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-success text-white ms-4" %>
      
  </header>
</div>

<% path = URI.parse(request.original_url).path.split('/')  %>
<div class='admin-sidebar-container'>
  <ul class="bg-light my-0 h-100 me-3  text-decoration-none py-3 shadow px-3"> 
    <h5 class="welcome-text px-2 text-center mt-3 fw-bold">Welcome back, </h5>
    <h5 class="welcome-text px-2 text-center mb-3 fw-bold"><%= current_user.fname + " " + current_user.lname %>!</h5>
    <li class="<%= "d-flex align-items-center rounded #{"active" if path.include?("users")}" %>" >
      <%= link_to admin_users_path, class:"w-100 h-100 px-3 py-2" do %>
        <i class="fa-regular fa-circle-user fs-5 me-2"></i>
        <span>Manage users</span>
      <% end %>
    </li>
    
    <li class="<%= "d-flex align-items-center rounded #{"active" if path.include?("albums")}" %>" >
      <%= link_to admin_albums_path, class:"w-100 h-100 px-3 py-2" do %>
        <i class="fa-regular fa-image me-2  fs-5"></i>
        <span>Manage albums</span>
      <% end %>
    </li>
    
    <li class="<%= "d-flex align-items-center rounded #{"active" if path.include?("photos")}" %>" >
      <%= link_to admin_photos_path, class:"w-100 h-100 px-3 py-2" do %>
        <i class="fa-regular fa-images me-2 fs-5"></i>
        <span>Manage photos</span>
      <% end %>
    </li>
  </ul>     

</div>

app/views/layouts/_header.html.erb
<div class="bg-primary py-1 d-flex justify-content-center px-0 px-md-3" id="header">
  <header class="header container py-2 d-flex align-items-center mx-0 mx-md-2 px-0">
    <%= link_to "Fotobook", root_path, class: "text-white h2 m-0 me-3 fw-bold text-decoration-none" %>
    <%= form_tag search_path, method: :get, class: "form-group search-form" do %>
      <div class="input-group w-0 position-relative px-2 d-none d-md-flex">
        <%= text_field_tag :key, "" , class: "form-control search-form__text--input w-auto rounded", placeholder: "Search for photos/albums..." %>
        <button class="input-icon-right btn btn-light cursor-pointer rounded">
          <i class="fa-solid fa-magnifying-glass text-dark"></i>
        </button>
      </div>
    <% end %>
    <span class="input-icon-right ms-2 cursor-pointer d-flex d-md-none rounded-circle align-items-center p-2">
      <i class="fa-solid fa-magnifying-glass text-white "></i>
    </span>
    
    <% if current_user %>
        <%= render "notifications/notifications", notifications: @notifications %>
        <%= link_to(profile_path(current_user), class: 'btn user-info d-flex align-items-center text-white text-decoration-none') do %>
            <%= image_tag(current_user.avatar, class: "user-info__avatar rounded-circle border") if current_user.avatar.attached? %>
            <span class="ms-2 text-nowrap"><%= current_user.fname + " " + current_user.lname %></span>
        <% end %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-success text-white ms-4 d-none d-md-block" %>
    <% else %>
        <%= link_to('Login', new_user_session_path, class: "ms-auto btn btn-light ms-4") %>
    <% end %>      
  </header>
</div>

app/views/layouts/_sidebar.html.erb
<% path = URI.parse(request.original_url).path.split('/') %>
<ul class="h-100 ps-5 position-fixed feeds-options d-none d-xl-block">
	<li class="my-2">
		<%= link_to "Feeds", root_path, class:"fs-5 #{"text-primary" unless path.include?("discovery")}" %>
	</li>
	<li class="my-2">
		<%= link_to "Discovery", "/discovery", class:"fs-5 #{"text-primary" if path.include?("discovery")}" %>
	</li>
	<li>
	</li>
</ul>     

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='wrapper' data-controller = "sidebar">
      <%= render 'layouts/admin_navbar' %>  
      <div class="container-fluid p-0">
        <div class ="d-flex flex-row align-items-start">
          <div class="admin-main-content w-100 me-3  d-flex flex-column position-relative">
            <%= yield %>
          </div>
          <%= turbo_frame_tag "remote_modal", target: "_top" %>
          <% flash.each do |type, msg| %>
             <%= render 'shared/flashes' %>
            <% end %>
        </div>
      </div>
    </div>
  </body>

  
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='wrapper bg-light'>
      <% if current_user && current_user.admin? %>
        <%= link_to "Go to Admin dashboard", admin_users_path, class: "btn btn-warning position-fixed bottom-0 end-0 z-100"  %>
      <% end %>
      <%= render 'layouts/header' %>  
      <%= render "layouts/sidebar" %>
      <div class="container-xl container-fluid position-relative main-content">
        <div class="row justify-content-center position-relative h-100">
          <div class="col-12 col-lg-10 col-xl-10 d-flex flex-column rounded bg-white p-4 ">
            <%= yield %>
            <%= turbo_frame_tag "remote_modal", target: "_top" %>
            <% flash.each do |type, msg| %>
             <%= render 'shared/flashes' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>

  
</html>